language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x

before_install:
  - go get -t -v ./...

script:
  - go mod verify
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go vet -v ./...
  - gofmt -l . && test -z "$(gofmt -l .)"

after_success:
  - bash <(curl -s https://codecov.io/bash)
